services:
  postgres:
    image: postgres:17
    container_name: procurement-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./procurement-api

    image: procurement-api
    container_name: procurement-backend
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./procurement-api:/app
      - /app/node_modules

    command: >
      sh -c "npx drizzle-kit migrate && npm run start:dev"

    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./procurement-fe

    container_name: procurement-frontend
    restart: unless-stopped

    ports:
      - "3001:3000"

    depends_on:
      - backend

    volumes:
      - ./procurement-fe:/app
      - /app/node_modules

    stdin_open: true
    tty: true

  drizzle-studio:
    image: procurement-api
    container_name: procurement-drizzle-studio
    restart: unless-stopped

    working_dir: /app

    environment:
      DATABASE_URL: ${DATABASE_URL}

    volumes:
      - ./procurement-api:/app
      - /app/node_modules

    ports:
      - "4984:4984"

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      npx drizzle-kit studio --host 0.0.0.0 --port 4984

  pgadmin:
    image: dpage/pgadmin4:9.6
    container_name: procurement-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "5050:80"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: